export const CATEGORIEDPRODUCT_LIST_REQUEST = "CATEGORIEDPRODUCT_LIST_REQUEST";
export const CATEGORIEDPRODUCT_LIST_SUCCESS = "CATEGORIEDPRODUCT_LIST_SUCCESS";
export const CATEGORIEDPRODUCT_LIST_FAIL = "CATEGORIEDPRODUCT_LIST_FAIL";
