export const ORDERSHOPER_LIST_REQUEST = "ORDERSHOPER_LIST_REQUEST";
export const ORDERSHOPER_LIST_SUCCESS = "ORDERSHOPER_LIST_SUCCESS";
export const ORDERSHOPER_LIST_FAIL = "ORDERSHOPER_LIST_FAIL";

export const ORDERSHOPER_CANCEL_REQUEST = "ORDERSHOPER_CANCEL_REQUEST";
export const ORDERSHOPER_CANCEL_SUCCESS = "ORDERSHOPER_CANCEL_SUCCESS";
export const ORDERSHOPER_CANCEL_FAIL = "ORDERSHOPER_CANCEL_FAIL";

export const ORDERSHOPER_RECIVE_DONE_REQUEST =
  "ORDERSHOPER_RECIVE_DONE_REQUEST";
export const ORDERSHOPER_RECIVE_DONE_SUCCESS =
  "ORDERSHOPER_RECIVE_DONE_SUCCESS";
export const ORDERSHOPER_RECIVE_DONE_FAIL = "ORDERSHOPER_RECIVE_DONE_FAIL";

export const ORDERSHOPER_RECIVE_ITEM_REQUEST =
  "ORDERSHOPER_RECIVE_ITEM_REQUEST";
export const ORDERSHOPER_RECIVE_ITEM_SUCCESS =
  "ORDERSHOPER_RECIVE_ITEM_SUCCESS";
export const ORDERSHOPER_RECIVE_ITEM_FAIL = "ORDERSHOPER_RECIVE_ITEM_FAIL";
