export const MERCHANTSTORE_REQUEST = "MERCHANTSTORE_REQUEST";
export const MERCHANTSTORE_SUCCESS = "MERCHANTSTORE_SUCCESS";
export const MERCHANTSTORE_FAIL = "MERCHANTSTORE_FAIL";

export const MERCHANT_ORDERITEM_STATUS_REQUEST =
  "MERCHANT_ORDERITEM_STATUS_REQUEST";
export const MERCHANT_ORDERITEM_STATUS_SUCCESS =
  "MERCHANT_ORDERITEM_STATUS_SUCCESS";
export const MERCHANT_ORDERITEM_STATUS_FAIL = "MERCHANT_ORDERITEM_STATUS_FAIL";

export const STORE_SALE_REQUEST = "STORE_SALE_REQUEST";
export const STORE_SALE_SUCCESS = "STORE_SALE_SUCCESS";
export const STORE_SALE_FAIL = "STORE_SALE_FAIL";
